name = "BedrockReloaded"
author = "SeriousFreezing"
version = "21.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd1fec39ccc43b44003a9da0849939f7863cb99c05b96c71175e1ecde01ed4dd"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
