name = "BedrockReloaded"
author = "SeriousFreezing"
version = "21.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8372ad95b9c8d2a43dd343f6cd1db7f2494683beefe5428998411fb9498f3e57"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
