name = "bedrock-reloaded"
author = "SeriousFreezing"
version = "41.0+beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36a3be5fe042d598086af3b36f665ac054c6a0932737e0920a0ff55a9aef3051"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = ["1.21.7", "26.1", "26.1.2"]
datapack-folder = "resources/datapack/optional"
