structureBlockLimit 64
scriptsAutoload false
railPowerLimit 9
quasiConnectivity 0
placementRotationFix false
pingPlayerListLimit 100
perfPermissionLevel 2
movableBlockEntities true
lightningKillsDropsFix true
forceloadLimit 10
fillUpdates false
commandTrackAI false
commandTick false
commandSpawn false
commandScript false
commandProfile false
commandPlayer false
commandPerimeterInfo false
commandLog false
commandInfo false
commandDraw false
commandDistance false
allowSpawningOfflinePlayers false
optimizedTNT true
lagFreeSpawning true
fastRedstoneDust true