version = 0
enableCloseWindow = false
enableJeiLeft = false
enableJeiRight = false
enableHover = false
enableTooltip = false
enableClickItem = false
enableOutput = false
enableDrag = false
enableSameItem = false
enableQuick = false
enableHoldItem = false
enableHoldZoomTransition = false
enableSelectedItemName = false
enableAttack = false
enableUse = false
enableLack = false
enableSelectMove = false
enableExp = false
enableArmor = false
enableChat = false
enableCloseChat = false
enableChatComp = false
enableBossShow = false
enableBossHide = false
enableBossHurt = false