mixin.feature.branding=false
mixin.feature.remove_telemetry=false
mixin.feature.snapshot_easter_egg=false
mixin.perf.dynamic_entity_renderers=true
mixin.perf.remove_biome_temperature_cache=false
mixin.perf.thread_priorities=false