name = "BedrockReloaded"
author = "SeriousFreezing"
version = "22.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e92bec394589f342c4c19d35174fdd37f8c1af94e85b8b90e8769a21d62b7714"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21.3"]
