snowMakingIce: false
snowReduceFallDamage: false
sustainGrassIfLayerMoreThanOne: false
sneakSnowball: false
fancySnowOnUpperSlab: false
rightClickToggleFancySnow: false
snow-cover:
  restoreOriginalBlocks: true
  replaceWorldgenFeature: false
  placeSnowOnBlock: false
  placeNaturally: false
accumulation:
  naturalMelting: false
  smoothAccumulation: true
  maxLayers: 12
  accumulatesDuringSnowstorm: false